languageCode = "en-us"
title = "The Rice Boat"
baseURL = "/"
theme = "massively"
googleanalytics = ""
disqusShortname = ""
disableKinds = ["taxonomy", "taxonomyTerm", "section"]

# [params]
  # set below parameter to define a favicon
  # favicon = "favicon.ico"
  # set to change date format
  # dateFormat = "2.1.2006"

# Below parameters can be set to override default post settings
[params.posts]
    folderName = "project"
    pageSize = "8"
    featuredPost = true
    paginationPages = 2
    showFirstLast = false
 
[languages]
[languages.en]
  languageName = "English"
[languages.es]
  languageName = "Español"
#[languages.fr]
#  languageName = "Français"
#  title = "Massively - Version Française"